source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'11.0'

target “DFLGQWebDemo” do
#use_frameworks! # 运用 Dynamic Framework
use_modular_headers!
    pod 'DFLGQWeb'
    pod 'ZXingObjC', '~> 3.6.4'

end

